serverAddr = "127.0.0.1"
serverPort = 9527
#认证
[auth]
token = "5E793FAD27AA713D"
[auth.retry]
initialDelay = 1
maxDelay = 10
maxRetries = 5

[tls]
enable = false
certFile = "cert/openssl/chain.pem"
keyFile = "cert/openssl/privkey.pem"
caFile = "cert/openssl/chain.pem"

[[proxies]]
name = "web1"
protocol = "http"
localIp = "localhost"
localPort = 8081
autoDomain = false
customDomains = ["a.domain1.com"]
status = 1

[[proxies]]
name = "web11"
protocol = "http"
localIp = "localhost"
localPort = 8030
autoDomain = true
subDomains = ["a", "b"]
status = 1
[proxies.basic_auth]
enable = true
users = [
    { user = "user1", pass = "pass1" },
    { user = "user2", pass = "pass2" }
]
[proxies.access_control]
enable = true
mode = "allow"
allow = ["43.135.115.160/32"]
deny = []

[[proxies]]
name = "fullstack2"
protocol = "http"
localIp = "localhost"
localPort = 8090
autoDomain = true
status = 1
encrypt = true
compress = true

[[proxies]]
name = "web2"
protocol = "http"
localIp = "localhost"
localPort = 8030
customDomains = ["etp.domain2.com"]
encrypt = false
compress = false
[proxies.access_control]
enable = true
mode = "allow"
allow = ["127.0.0.1"]
[proxies.basic_auth]
enable = true
users = [
    { user = "user1", pass = "123" },
    { user = "user2", pass = "456" }
]
[[proxies]]
name = "web22"
protocol = "http"
localIp = "localhost"
localPort = 8030
customDomains = ["etp2.domain2.com"]
encrypt = false
compress = false
[proxies.access_control]
enable = true
mode = "allow"
deny = ["127.0.0.2"]

[[proxies]]
name = "mysql"
protocol = "tcp"
localPort = 3306
remotePort = 3307
status = 1
encrypt = false
compress = false
#tunnelType = "shared" #dedicated
[proxies.bandwidth] #带宽限制
limit = "1M" #总带宽限制(可选)
limitIn = "512K" #入口带宽限制(可选)
limitOut = "512K" #出口带宽限制(可选)
[proxies.access_control] #访问控制
enable = true
mode = "allow"
allow = ["127.0.0.1"]
deny = []
[[proxies]]
name = "mysql2"
protocol = "tcp"
localPort = 3306
remotePort = 3308
status = 1
encrypt = false
compress = false

[proxies.access_control]
enable = true
mode = "allow"
allow = ["127.0.0.2"]
deny = []

[[proxies]]
name = "redis"
protocol = "tcp"
localPort = 6379
remotePort = 6380
status = 1
encrypt = true
compress = true

#日志
[log]
level = "debug"
path = "log"
name = "etpc.log"
archivePattern = "etpc.%d{yyyy-MM-dd}.log"
logPattern = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
maxHistory = 30
totalSizeCap = "3GB"