serverAddr = "127.0.0.1"
serverPort = 9527
#认证
[auth]
token = "token"

[tls]
eable = false
certPath = "cert/client.p12"
storePassPath = "jesjH9JNLKY3"
mutual = true #开启双向认证

# 三个字段互斥，优先级：customDomains > subDomains > autoDomain 后面两个必须配置基础域名
[[proxies]]
name = "web1"
protocol = "http"
localIp = "localhost"
localPort = 1024
autoDomain = true
customDomains = ["a.domain1.com"]
status=0

[[proxies]]
name = "web2"
protocol = "http"
localIp = "localhost"
localPort = 8082
customDomains = ["a.domain2.com", "b.domain2.com"]

[[proxies]]
name = "mysql"
protocol = "tcp"
localPort = 3306
remotePort=3307
status = 1
encrypt = true
compress = true

[[proxies]]
name = "redis"
protocol = "tcp"
localPort = 6379
remotePort=6380
status = 1
encrypt = true
compress = true

#日志
[log]
level = "debug"
path = "log"
name = "etpc.log"
archivePattern = "etpc.%d{yyyy-MM-dd}.log"
logPattern = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
maxHistory = 30
totalSizeCap = "3GB"