host = "0.0.0.0"
bindPort = 9527
httpProxyPort = 80
httpsProxyPort = 8443
baseDomains = ["domain1.com", "domain2.com"]
# TLS
[tls]
enable = false
certPath = "cert/server.p12"
keyPath = "3FbV8R8VW49O"
storePassPath = "3FbV8R8VW49O"

[access_tokens]
desc = "windows"
token = "token"
maxClients = 2

[access_tokens]
desc = "mac"
token = "token2"
maxClients = 2

#日志
[log]
level = "debug"
path = "log"
name = "etps.log"
archivePattern = "etps.%d{yyyy-MM-dd}.log"
logPattern = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
maxHistory = 30
totalSizeCap = "3GB"

#管理界面
[dashboard]
enable = true
#addr = "localhost"
port = 8030
reset = true
username = "admin"
password = "123456"
#公网端口分配范围
[port_range]
start = 8000
end = 8009
