bindPort = 9527
tls = true

[keystore]
path = "./cert/server.p12"
keyPass = "3FbV8R8VW49O"
storePass = "3FbV8R8VW49O"

[[clients]]
secretKey = "4b0063baa5ae47c2910fc25265aae4b9"
name = "windows"

[[clients.proxies]]
localPort = 3306
name = "mysql"
remotePort = 3307
type = "tcp"
status=1 #默认是1

[[clients.proxies]]
localPort = 6379
name = "redis"
remotePort = 6380
type = "tcp"
status=0

[dashboard]
enable_tls = false
password = "123456"
port = 8080
enable = true
addr = "localhost"
username = "admin"

[[clients]]
secretKey = "4b0063baa5ae47c2910fc25265aae4109"
name = "macos"
[log]
level = "info"
pattern = ""
