tls = false
bindPort = 9527

[keystore]
path = "./cert/server.p12"
keyPass = "3FbV8R8VW49O"
storePass = "3FbV8R8VW49O"

#[[clients]]
#secretKey = "4b0063baa5ae47c2910fc25265aae4109"
#name = "macos"
#
#[[clients.proxies]]
#localPort = 3306
#name = "123456"
#remotePort = 9879
#type = "tcp"
#

[log]
level = "info"
pattern = ""

[dashboard]
enable_tls = false
password = "123456"
port = 8080
enable = true
addr = "localhost"
username = "admin"
