tls = false
bindPort = 9527

[keystore]
path = "./cert/server.p12"
keyPass = "3FbV8R8VW49O"
storePass = "3FbV8R8VW49O"

[[clients]]
secretKey = "4b0063baa5ae47c2910fc25265aae4132"
name = "静态客户端"

#[[clients.proxies]]
#localPort = 3306
#name = "静态配置"
#remotePort = 9879
#type = "tcp"
#
#---------------------------日志--------------------------------#
[log]
level = "info"
pattern = ""

[dashboard]
enable = true
addr = "localhost"
port = 8080
username = "admin"
password = "123456"


