host = "0.0.0.0"
bindPort = 9527
# TLS
tls = false
[keystore]
path = "cert/server.p12"
keyPass = "3FbV8R8VW49O"
storePass = "3FbV8R8VW49O"
#
[[clients]]
secretKey = "your-secret-key"
name = "静态客户端"
##---------------------------日志--------------------------------#
[log]
level = "debug"
path = "log"
name = "etps.log"
archivePattern = "etps.%d{yyyy-MM-dd}.log"
logPattern = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
maxHistory = 30
totalSizeCap = "3GB"

[dashboard]
enable = true
#addr = "localhost"
port = 8020
reset = true
username = "a"
password = "1"
#
#端口范围
[port_range]
start = 8000
end = 8009
