host = "0.0.0.0"
bindPort = 9527
httpProxyPort = 8080
httpsProxyPort = 8443
# TLS
tls =true
[keystore]
path = "cert/server.p12"
keyPass = "3FbV8R8VW49O"
storePass = "3FbV8R8VW49O"
#客户端
[[clients]]
secretKey = "your-secret-key"
name = "客户端"
[[clients.proxies]]
name = "web"
type = "http"
localIP="localhost"
localPort = 8081
domains = ["a.local.cc", "b.local.cc"]
status = 1 #是否开启代理

[[clients.proxies]]
name = "web2"
type = "http"
localIP="localhost"
localPort = 3000
domains = ["c.local.cc"]
status = 1 #是否开启代理


[[clients.proxies]]
name = "mysql"
type = "tcp"
localPort = 3306
status = 1 #是否开启代理
#日志
[log]
level = "debug"
path = "log"
name = "etps.log"
archivePattern = "etps.%d{yyyy-MM-dd}.log"
logPattern = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
maxHistory = 30
totalSizeCap = "3GB"
#管理界面
[dashboard]
enable = true
#addr = "localhost"
port = 8030
reset = true
username = "admin"
password = "123456"
#公网端口分配范围
[port_range]
start = 8000
end = 8009
