etp:
  client:
    enabled: true #是否开启etp代理，默认为关闭状态
    server-addr: 129.204.59.184 #服务器地址
    secret-key: 273483b4bf904d3aaafd0bf6c1ab3ab1 #认证Token

#    tls: false
#    truststore:
#      path: cert/client.p12 #证书路径
#      store-pass: jesjH9JNLKY3 # 密钥
#
#    initial-delay-sec: 2 #首次连接失败延迟
#    max-delay-sec: 10 # 最大延迟秒数
#    max-retries: 8 # 最大重试次数
