spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  profiles:
    active: mysql
logging:
  level:
    com.xiaoniucode.etp: debug
server:
  servlet:
    context-path: /


jwt:
  secret: test
  expiration: 3600000

security:
  permit-all:
    paths:
      - /api/auth/login
      - /api/captcha
      - /login.html
      - /layui/**
      - /assets/**
      - /static/**