etp:
  client:
    enabled: true
    server-addr: 129.204.59.184
    secret-key: 273483b4bf904d3aaafd0bf6c1ab3ab1
    tls: false
    truststore:
      path: /Users/liuxin/Desktop/etp/cert/client.p12
      store-pass: test
server:
  port: 8080
