serverAddr = "127.0.0.1"
serverPort = 9527
secretKey = "your-secret-key"
#################TLS加密配置#################
#tls = false
#[truststore]
#path = "/path/cert/client.p12"
#storePass = "your-store-pass"

#################日志配置#################
#[log]
#level = "info" #默认为info
#pattern = ""
#path=""
