serverAddr = "127.0.0.1"
serverPort = 9527
secretKey = "your-secret-key"
#################连接超时配置#################
#initialDelaySec = 2 #首次连接失败延迟时间
#maxRetries = 8 #最大重试次数
#maxDelaySec = 10 #每次延迟秒数
#################TLS加密配置#################
#tls = false
#[truststore]
#path = "/path/cert/client.p12"
#storePass = "your-store-pass"

#################日志配置####################
#[log]
#level = "debug"
#path = "log"
#name = "etpc.log"
#archivePattern = "etpc.%d{yyyy-MM-dd}.log.gz"
#logPattern = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#maxHistory = 30
#totalSizeCap = "3GB"
