serverAddr = "127.0.0.1"
serverPort = 9527
secretKey = "your-secret-key"
#################连接超时配置#################
#initialDelaySec = 2 #首次连接失败延迟时间
#maxRetries = 8 #最大重试次数
#maxDelaySec = 10 #每次延迟秒数
#################TLS加密配置#################
#tls = false
#[truststore]
#path = "/path/cert/client.p12"
#storePass = "your-store-pass"

#################日志配置####################
#[log]
#level = "info" #默认为info
#pattern = ""
#path=""
