#################服务配置#################
#host="0.0.0.0"
bindPort = 9527
#################TLS加密配置#################
#tls = false
#[keystore]
#path = "/path/cert/server.p12"
#keyPass = "your-keypass"
#storePass = "your-storepass"

#################客户端代理配置#################
#----------------客户端1----------------#
[[clients]]
name = "windows"
secretKey = "your-secret-key"

[[clients.proxies]]
name = "mysql"
type = "tcp"
localPort = 3306
remotePort = 3307
#status=1 #是否开启映射，默认为1

[[clients.proxies]]
name = "redis"
type = "tcp"
localPort = 6379
remotePort = 6380

#[[clients.proxies]]
#name = "web"
#type = "tcp"
#localPort = 8080
#remotePort = 8085

#----------------客户端2----------------#
#[[clients]]
#name = "macos"
#secretKey = "your-secret-key"

#[[clients.proxies]]
#name = "mysql"
#type = "tcp"
#localPort = 3306
#remotePort = 3307

#################日志配置#################
#[log]
#level = "debug"
#pattern = ""
#path=""
#################管理面板配置#################
#[dashboard]
#enable = true
#addr = "localhost"
#port = 8080
#username = "admin"
#password = "123456"
