etp:
  client:
    enable: true
#    server-addr: 127.0.0.1
#    server-port: 9527
#    protocol: http
#    local-ip: 127.0.0.1
    auth:
      token: 5E793FAD27AA713D
#      retry:
#        max-retries: 1
#        max-delay: 10
#        initial-delay: 2








