etp:
  client:
    enable: true
#    server-addr: 127.0.0.1
#    server-port: 9527
#    protocol: http
#    local-ip: 127.0.0.1
    access-control:
      allow:
        - localhost
        - 192.168.0.1
      enable: true
      mode: allow
      deny:
        - 127.0.0.2
        - 127.0.0.3
    auth:
      token: 5E793FAD27AA713D
#      retry:
#        max-retries: 1
#        max-delay: 10
#        initial-delay: 2








